/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Team, Player, Tournament, Match, Settings } from './types';

export const initialTeams: Team[] = [
  {
    id: 't1',
    name: 'Green Eagles',
    emoji: '🦅',
    color: '#16A34A',
    captain: 'p1',
    vc: 'p2',
    ground: 'Emirates Stadium',
    format: 'All Formats',
    players: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11'],
    wins: 18,
    losses: 6,
    draws: 1,
    created: '2024'
  },
  {
    id: 't2',
    name: 'Royal Lions',
    emoji: '🦁',
    color: '#1d4ed8',
    captain: 'p12',
    vc: 'p13',
    ground: 'Lions Den',
    format: 'T20 & ODI',
    players: ['p12', 'p13', 'p14', 'p15', 'p16', 'p17', 'p18', 'p19', 'p20', 'p21', 'p22'],
    wins: 14,
    losses: 9,
    draws: 2,
    created: '2024'
  },
  {
    id: 't3',
    name: 'Storm Riders',
    emoji: '⛈️',
    color: '#7c3aed',
    captain: 'p23',
    vc: 'p24',
    ground: 'City Ground',
    format: 'T20 Only',
    players: ['p23', 'p24', 'p25', 'p26', 'p27', 'p28', 'p29', 'p30', 'p31', 'p32', 'p33'],
    wins: 16,
    losses: 7,
    draws: 1,
    created: '2023'
  },
  {
    id: 't4',
    name: 'Desert Kings',
    emoji: '👑',
    color: '#b45309',
    captain: 'p34',
    vc: 'p35',
    ground: 'National Stadium',
    format: 'All Formats',
    players: ['p34', 'p35', 'p36', 'p37', 'p38', 'p39', 'p40', 'p41', 'p42', 'p43', 'p44'],
    wins: 20,
    losses: 5,
    draws: 2,
    created: '2023'
  },
  {
    id: 't5',
    name: 'Sea Wolves',
    emoji: '🌊',
    color: '#0891b2',
    captain: 'p45',
    vc: 'p46',
    ground: 'Coastal Arena',
    format: 'T20 & Test',
    players: ['p45', 'p46', 'p47', 'p48', 'p49', 'p50', 'p51', 'p52', 'p53', 'p54', 'p55'],
    wins: 11,
    losses: 13,
    draws: 3,
    created: '2024'
  },
  {
    id: 't6',
    name: 'Valley Warriors',
    emoji: '⚔️',
    color: '#dc2626',
    captain: 'p56',
    vc: 'p57',
    ground: 'Mountain View',
    format: 'ODI & T20',
    players: ['p56', 'p57', 'p58', 'p59', 'p60', 'p61', 'p62', 'p63', 'p64', 'p65', 'p66'],
    wins: 13,
    losses: 10,
    draws: 2,
    created: '2023'
  }
];

export const initialPlayers: Player[] = [
  {
    id: 'p1',
    name: 'Ahmed Khan',
    initials: 'AK',
    age: 24,
    team: 't1',
    role: 'Batsman',
    bat: 'Right',
    bowl: 'None',
    matches: 23,
    runs: 1842,
    balls_faced: 1285,
    hs: 128,
    fifties: 11,
    hundreds: 4,
    fours: 186,
    sixes: 42,
    wickets: 0,
    overs: 0,
    runs_given: 0,
    wbest: '—',
    maidens: 0,
    catches: 8,
    stumpings: 0
  },
  {
    id: 'p2',
    name: 'Faisal Butt',
    initials: 'FB',
    age: 28,
    team: 't1',
    role: 'Bowler',
    bat: 'Right',
    bowl: 'Right-arm Fast',
    matches: 23,
    runs: 142,
    balls_faced: 98,
    hs: 28,
    fifties: 0,
    hundreds: 0,
    fours: 12,
    sixes: 2,
    wickets: 52,
    overs: 88,
    runs_given: 632,
    wbest: '5/22',
    maidens: 4,
    catches: 5,
    stumpings: 0
  },
  {
    id: 'p3',
    name: 'Muhammad Hassan',
    initials: 'MH',
    age: 22,
    team: 't1',
    role: 'All-Rounder',
    bat: 'Left',
    bowl: 'Left-arm Medium',
    matches: 19,
    runs: 724,
    balls_faced: 548,
    hs: 84,
    fifties: 5,
    hundreds: 1,
    fours: 68,
    sixes: 22,
    wickets: 31,
    overs: 72,
    runs_given: 498,
    wbest: '4/18',
    maidens: 2,
    catches: 10,
    stumpings: 0
  },
  {
    id: 'p4',
    name: 'Kareem Malik',
    initials: 'KM',
    age: 26,
    team: 't1',
    role: 'Batsman',
    bat: 'Left',
    bowl: 'None',
    matches: 20,
    runs: 886,
    balls_faced: 712,
    hs: 96,
    fifties: 6,
    hundreds: 0,
    fours: 92,
    sixes: 14,
    wickets: 0,
    overs: 0,
    runs_given: 0,
    wbest: '—',
    maidens: 0,
    catches: 7,
    stumpings: 0
  },
  {
    id: 'p5',
    name: 'Zafar Iqbal',
    initials: 'ZI',
    age: 31,
    team: 't1',
    role: 'Wicket-Keeper',
    bat: 'Right',
    bowl: 'None',
    matches: 23,
    runs: 512,
    balls_faced: 488,
    hs: 67,
    fifties: 3,
    hundreds: 0,
    fours: 44,
    sixes: 8,
    wickets: 0,
    overs: 0,
    runs_given: 0,
    wbest: '—',
    maidens: 0,
    catches: 28,
    stumpings: 11
  },
  {
    id: 'p12',
    name: 'Rahul Sharma',
    initials: 'RS',
    age: 27,
    team: 't2',
    role: 'Bowler',
    bat: 'Right',
    bowl: 'Right-arm Fast',
    matches: 28,
    runs: 156,
    balls_faced: 102,
    hs: 24,
    fifties: 0,
    hundreds: 0,
    fours: 12,
    sixes: 2,
    wickets: 67,
    overs: 112,
    runs_given: 806,
    wbest: '5/18',
    maidens: 6,
    catches: 12,
    stumpings: 0
  },
  {
    id: 'p13',
    name: 'Arjun Nair',
    initials: 'AN',
    age: 25,
    team: 't2',
    role: 'Batsman',
    bat: 'Right',
    bowl: 'None',
    matches: 24,
    runs: 1124,
    balls_faced: 896,
    hs: 112,
    fifties: 8,
    hundreds: 2,
    fours: 104,
    sixes: 24,
    wickets: 0,
    overs: 0,
    runs_given: 0,
    wbest: '—',
    maidens: 0,
    catches: 9,
    stumpings: 0
  },
  {
    id: 'p14',
    name: 'Vikram Patel',
    initials: 'VP',
    age: 29,
    team: 't2',
    role: 'All-Rounder',
    bat: 'Right',
    bowl: 'Off-spin',
    matches: 22,
    runs: 648,
    balls_faced: 512,
    hs: 78,
    fifties: 4,
    hundreds: 0,
    fours: 58,
    sixes: 16,
    wickets: 28,
    overs: 68,
    runs_given: 452,
    wbest: '3/24',
    maidens: 3,
    catches: 14,
    stumpings: 0
  },
  {
    id: 'p23',
    name: 'Zaid Anwar',
    initials: 'ZA',
    age: 26,
    team: 't3',
    role: 'Batsman',
    bat: 'Left',
    bowl: 'None',
    matches: 31,
    runs: 2134,
    balls_faced: 1568,
    hs: 142,
    fifties: 14,
    hundreds: 6,
    fours: 224,
    sixes: 58,
    wickets: 0,
    overs: 0,
    runs_given: 0,
    wbest: '—',
    maidens: 0,
    catches: 11,
    stumpings: 0
  },
  {
    id: 'p24',
    name: 'Tariq Shah',
    initials: 'TS',
    age: 24,
    team: 't3',
    role: 'Bowler',
    bat: 'Right',
    bowl: 'Leg-spin',
    matches: 28,
    runs: 188,
    balls_faced: 142,
    hs: 32,
    fifties: 0,
    hundreds: 0,
    fours: 18,
    sixes: 4,
    wickets: 58,
    overs: 108,
    runs_given: 786,
    wbest: '4/28',
    maidens: 5,
    catches: 8,
    stumpings: 0
  },
  {
    id: 'p34',
    name: 'Fahad Ali',
    initials: 'FA',
    age: 29,
    team: 't4',
    role: 'Bowler',
    bat: 'Right',
    bowl: 'Right-arm Fast',
    matches: 42,
    runs: 213,
    balls_faced: 168,
    hs: 28,
    fifties: 0,
    hundreds: 0,
    fours: 18,
    sixes: 4,
    wickets: 89,
    overs: 168,
    runs_given: 1026,
    wbest: '6/22',
    maidens: 8,
    catches: 14,
    stumpings: 0
  },
  {
    id: 'p35',
    name: 'Omar Sheikh',
    initials: 'OS',
    age: 24,
    team: 't4',
    role: 'Batsman',
    bat: 'Right',
    bowl: 'None',
    matches: 35,
    runs: 1688,
    balls_faced: 1286,
    hs: 118,
    fifties: 12,
    hundreds: 3,
    fours: 168,
    sixes: 36,
    wickets: 0,
    overs: 0,
    runs_given: 0,
    wbest: '—',
    maidens: 0,
    catches: 9,
    stumpings: 0
  },
  {
    id: 'p45',
    name: 'Kiran Rao',
    initials: 'KR',
    age: 32,
    team: 't5',
    role: 'Batsman',
    bat: 'Left',
    bowl: 'None',
    matches: 44,
    runs: 2688,
    balls_faced: 2188,
    hs: 168,
    fifties: 18,
    hundreds: 8,
    fours: 272,
    sixes: 46,
    wickets: 0,
    overs: 0,
    runs_given: 0,
    wbest: '—',
    maidens: 0,
    catches: 16,
    stumpings: 0
  },
  {
    id: 'p46',
    name: 'Dev Menon',
    initials: 'DM',
    age: 26,
    team: 't5',
    role: 'All-Rounder',
    bat: 'Right',
    bowl: 'Right-arm Medium',
    matches: 32,
    runs: 886,
    balls_faced: 712,
    hs: 88,
    fifties: 6,
    hundreds: 1,
    fours: 88,
    sixes: 22,
    wickets: 44,
    overs: 96,
    runs_given: 688,
    wbest: '4/32',
    maidens: 4,
    catches: 12,
    stumpings: 0
  },
  {
    id: 'p56',
    name: 'Ali Hassan',
    initials: 'AH',
    age: 27,
    team: 't6',
    role: 'Batsman',
    bat: 'Right',
    bowl: 'None',
    matches: 26,
    runs: 1244,
    balls_faced: 1012,
    hs: 108,
    fifties: 9,
    hundreds: 2,
    fours: 124,
    sixes: 26,
    wickets: 0,
    overs: 0,
    runs_given: 0,
    wbest: '—',
    maidens: 0,
    catches: 8,
    stumpings: 0
  },
  {
    id: 'p57',
    name: 'Raza Mir',
    initials: 'RM',
    age: 28,
    team: 't6',
    role: 'Bowler',
    bat: 'Right',
    bowl: 'Left-arm spin',
    matches: 30,
    runs: 224,
    balls_faced: 188,
    hs: 38,
    fifties: 0,
    hundreds: 0,
    fours: 22,
    sixes: 4,
    wickets: 62,
    overs: 118,
    runs_given: 898,
    wbest: '5/34',
    maidens: 7,
    catches: 10,
    stumpings: 0
  }
];

export const initialTournaments: Tournament[] = [
  {
    id: 'tr1',
    name: 'Summer T20 League 2026',
    type: 'League',
    format: 'T20',
    teams: ['t1', 't2', 't3', 't4', 't5', 't6'],
    status: 'Ongoing',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    matches: 20,
    played: 13,
    winner: null,
    pointsTable: [
      { teamId: 't1', p: 6, w: 5, l: 1, d: 0, pts: 10, nrr: 1.42 },
      { teamId: 't4', p: 6, w: 4, l: 2, d: 0, pts: 8, nrr: 0.87 },
      { teamId: 't3', p: 6, w: 4, l: 2, d: 0, pts: 8, nrr: 0.64 },
      { teamId: 't6', p: 6, w: 3, l: 3, d: 0, pts: 6, nrr: 0.12 },
      { teamId: 't2', p: 5, w: 2, l: 3, d: 0, pts: 4, nrr: -0.32 },
      { teamId: 't5', p: 6, w: 1, l: 5, d: 0, pts: 2, nrr: -1.22 }
    ]
  },
  {
    id: 'tr2',
    name: 'City Cup 2026',
    type: 'Knockout',
    format: 'T20',
    teams: ['t1', 't2', 't3', 't4', 't5', 't6'],
    status: 'Ongoing',
    startDate: '2026-05-01',
    endDate: '2026-07-15',
    matches: 15,
    played: 8,
    winner: null,
    pointsTable: []
  }
];

export const initialMatches: Match[] = [
  {
    id: 'm1',
    team1: 't1',
    team2: 't2',
    format: 'T20',
    venue: 'Emirates Stadium',
    date: '2026-05-30',
    status: 'Live',
    tournament: 'tr1',
    team1Squad: ['p1', 'p2', 'p3', 'p4', 'p5'],
    team2Squad: ['p12', 'p13', 'p14'],
    innings: [
      {
        batting: 't1',
        bowling: 't2',
        total: 187,
        wickets: 4,
        overs: 19,
        balls: 3,
        extras: { wd: 8, nb: 3, b: 2, lb: 1 },
        batting_card: [
          { playerId: 'p4', runs: 32, balls: 28, fours: 4, sixes: 1, dismissed: 'c Sharma b Rahman', bowler: 'p13' },
          { playerId: 'p23', runs: 18, balls: 14, fours: 2, sixes: 0, dismissed: 'b Sharma', bowler: 'p12' },
          { playerId: 'p3', runs: 26, balls: 22, fours: 3, sixes: 0, dismissed: 'lbw b Sharma', bowler: 'p12' },
          { playerId: 'p1', runs: 87, balls: 61, fours: 9, sixes: 3, dismissed: 'not out', bowler: null },
          { playerId: 'p5', runs: 24, balls: 18, fours: 3, sixes: 0, dismissed: 'not out', bowler: null }
        ],
        bowling_card: [
          { playerId: 'p12', overs: 4, maidens: 0, runs: 28, wickets: 3, noballs: 1, wides: 2 },
          { playerId: 'p14', overs: 4, maidens: 0, runs: 35, wickets: 1, noballs: 1, wides: 3 },
          { playerId: 'p13', overs: 4, maidens: 0, runs: 42, wickets: 0, noballs: 0, wides: 2 },
          { playerId: 'p46', overs: 4, maidens: 1, runs: 38, wickets: 0, noballs: 1, wides: 1 },
          { playerId: 'p57', overs: 3, balls_this_over: 3, maidens: 0, runs: 30, wickets: 0, noballs: 0, wides: 0 }
        ],
        fow: [
          { wkt: 1, score: 42, over: '6.2', player: 'p4' },
          { wkt: 2, score: 72, over: '10.4', player: 'p23' },
          { wkt: 3, score: 115, over: '15.1', player: 'p3' },
          { wkt: 4, score: 149, over: '17.3', player: 'p5' }
        ],
        partnerships: [
          { bat1: 'p4', bat2: 'p23', runs: 42, balls: 40 },
          { bat1: 'p4', bat2: 'p3', runs: 30, balls: 26 },
          { bat1: 'p3', bat2: 'p1', runs: 43, balls: 38 },
          { bat1: 'p5', bat2: 'p1', runs: 38, balls: 24 }
        ],
        obo: [
          [8, 1],
          [12, 0],
          [7, 0],
          [6, 0],
          [9, 0],
          [4, 0],
          [10, 1],
          [13, 0],
          [8, 0],
          [6, 0],
          [11, 0],
          [7, 1],
          [14, 0],
          [8, 0],
          [9, 1],
          [12, 0],
          [14, 0],
          [10, 0],
          [16, 0],
          [9, 0]
        ],
        deliveries: []
      }
    ],
    currentInnings: 0,
    target: null,
    result: null
  },
  {
    id: 'm2',
    team1: 't3',
    team2: 't6',
    format: 'ODI',
    venue: 'City Ground',
    date: '2026-05-29',
    status: 'Completed',
    tournament: 'tr1',
    result: { winner: 't3', margin: '47 runs', mvp: 'p23' },
    team1Squad: ['p23', 'p24'],
    team2Squad: ['p56', 'p57'],
    innings: [
      {
        batting: 't3',
        bowling: 't6',
        total: 268,
        wickets: 6,
        overs: 50,
        balls: 0,
        extras: { wd: 12, nb: 4, b: 3, lb: 5 },
        batting_card: [{ playerId: 'p23', runs: 84, balls: 92, fours: 10, sixes: 3, dismissed: 'c Ali b Mir', bowler: 'p57' }],
        bowling_card: [],
        fow: [],
        partnerships: [],
        obo: [],
        deliveries: []
      },
      {
        batting: 't6',
        bowling: 't3',
        total: 221,
        wickets: 10,
        overs: 44,
        balls: 3,
        extras: { wd: 8, nb: 2, b: 1, lb: 4 },
        batting_card: [{ playerId: 'p56', runs: 62, balls: 78, fours: 7, sixes: 1, dismissed: 'b Shah', bowler: 'p24' }],
        bowling_card: [],
        fow: [],
        partnerships: [],
        obo: [],
        deliveries: []
      }
    ],
    currentInnings: 1,
    target: 269
  }
];

export const defaultSettings: Settings = {
  format: 'T20',
  overs: 20,
  pp: 6,
  bowlerOvers: 4,
  adminName: 'Faheem Akram',
  venue: 'Emirates Cricket Club',
  season: '2026',
  themeColor: 'green',
  themeFont: 'Rajdhani'
};
